# Generated by Django 3.2.13 on 2023-09-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdovinicius', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=70)),
                ('continente', models.CharField(max_length=50)),
            ],
        ),
    ]
