# Generated by Django 3.2.13 on 2023-09-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdovinicius', '0002_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available', models.CharField(max_length=100)),
            ],
        ),
    ]
